// Mock data for the SOFIXE ERP/CRM system

export const dashboardStats = {
  revenue: {
    current: 2450000,
    previous: 2100000,
    change: 16.7,
  },
  activeProjects: {
    current: 24,
    previous: 21,
    change: 14.3,
  },
  employees: {
    current: 156,
    previous: 148,
    change: 5.4,
  },
  clients: {
    current: 89,
    previous: 82,
    change: 8.5,
  },
}

export const revenueData = [
  { month: "Jan", revenue: 180000, expenses: 120000 },
  { month: "Feb", revenue: 195000, expenses: 125000 },
  { month: "Mar", revenue: 210000, expenses: 135000 },
  { month: "Apr", revenue: 225000, expenses: 140000 },
  { month: "May", revenue: 240000, expenses: 145000 },
  { month: "Jun", revenue: 255000, expenses: 150000 },
]

export const projectStatusData = [
  { status: "In Progress", count: 12, color: "hsl(var(--chart-1))" },
  { status: "Planning", count: 5, color: "hsl(var(--chart-2))" },
  { status: "On Hold", count: 3, color: "hsl(var(--chart-3))" },
  { status: "Completed", count: 4, color: "hsl(var(--chart-4))" },
]

export const recentActivities = [
  {
    id: "1",
    type: "project",
    title: "New project started",
    description: "Villa Construction - Phase 1",
    time: "2 hours ago",
    user: "John Manager",
  },
  {
    id: "2",
    type: "client",
    title: "New client added",
    description: "ABC Construction Ltd.",
    time: "5 hours ago",
    user: "Sarah Sales",
  },
  {
    id: "3",
    type: "invoice",
    title: "Invoice paid",
    description: "Invoice #INV-2024-045 - $45,000",
    time: "1 day ago",
    user: "Finance Team",
  },
  {
    id: "4",
    type: "employee",
    title: "New employee onboarded",
    description: "Mike Johnson - Site Engineer",
    time: "2 days ago",
    user: "HR Department",
  },
  {
    id: "5",
    type: "stock",
    title: "Stock alert",
    description: "Cement inventory below threshold",
    time: "3 days ago",
    user: "Stock Manager",
  },
]

export const upcomingTasks = [
  {
    id: "1",
    title: "Site inspection - Villa Project",
    dueDate: "2024-01-15",
    priority: "high",
    assignee: "John Doe",
  },
  {
    id: "2",
    title: "Client meeting - ABC Corp",
    dueDate: "2024-01-16",
    priority: "medium",
    assignee: "Sarah Smith",
  },
  {
    id: "3",
    title: "Budget review - Q1 2024",
    dueDate: "2024-01-18",
    priority: "high",
    assignee: "Finance Team",
  },
  {
    id: "4",
    title: "Equipment maintenance",
    dueDate: "2024-01-20",
    priority: "low",
    assignee: "Mike Johnson",
  },
]

export const clients = [
  {
    id: "1",
    name: "ABC Construction Ltd.",
    email: "contact@abcconstruction.com",
    phone: "+1 (555) 123-4567",
    address: "123 Main St, New York, NY 10001",
    status: "active",
    totalProjects: 5,
    totalRevenue: 450000,
    lastContact: "2024-01-10",
    contactPerson: "John Smith",
  },
  {
    id: "2",
    name: "BuildRight Corp",
    email: "info@buildright.com",
    phone: "+1 (555) 234-5678",
    address: "456 Oak Ave, Los Angeles, CA 90001",
    status: "active",
    totalProjects: 3,
    totalRevenue: 280000,
    lastContact: "2024-01-08",
    contactPerson: "Sarah Johnson",
  },
  {
    id: "3",
    name: "Metro Developers",
    email: "contact@metrodev.com",
    phone: "+1 (555) 345-6789",
    address: "789 Pine Rd, Chicago, IL 60601",
    status: "prospect",
    totalProjects: 0,
    totalRevenue: 0,
    lastContact: "2024-01-12",
    contactPerson: "Mike Davis",
  },
  {
    id: "4",
    name: "Urban Builders Inc.",
    email: "hello@urbanbuilders.com",
    phone: "+1 (555) 456-7890",
    address: "321 Elm St, Houston, TX 77001",
    status: "active",
    totalProjects: 7,
    totalRevenue: 620000,
    lastContact: "2024-01-05",
    contactPerson: "Emily Brown",
  },
  {
    id: "5",
    name: "Skyline Properties",
    email: "info@skylineprops.com",
    phone: "+1 (555) 567-8901",
    address: "654 Maple Dr, Phoenix, AZ 85001",
    status: "inactive",
    totalProjects: 2,
    totalRevenue: 150000,
    lastContact: "2023-12-15",
    contactPerson: "David Wilson",
  },
]

export const quotes = [
  {
    id: "QT-2024-001",
    clientId: "3",
    clientName: "Metro Developers",
    projectName: "Office Complex Renovation",
    amount: 125000,
    status: "pending",
    validUntil: "2024-02-15",
    createdDate: "2024-01-10",
    items: [
      { description: "Structural work", quantity: 1, unitPrice: 45000, total: 45000 },
      { description: "Electrical installation", quantity: 1, unitPrice: 35000, total: 35000 },
      { description: "Plumbing", quantity: 1, unitPrice: 25000, total: 25000 },
      { description: "Finishing work", quantity: 1, unitPrice: 20000, total: 20000 },
    ],
  },
  {
    id: "QT-2024-002",
    clientId: "1",
    clientName: "ABC Construction Ltd.",
    projectName: "Residential Building - Phase 2",
    amount: 285000,
    status: "approved",
    validUntil: "2024-02-20",
    createdDate: "2024-01-08",
    items: [
      { description: "Foundation work", quantity: 1, unitPrice: 85000, total: 85000 },
      { description: "Structural framework", quantity: 1, unitPrice: 120000, total: 120000 },
      { description: "Roofing", quantity: 1, unitPrice: 45000, total: 45000 },
      { description: "Windows and doors", quantity: 1, unitPrice: 35000, total: 35000 },
    ],
  },
  {
    id: "QT-2024-003",
    clientId: "2",
    clientName: "BuildRight Corp",
    projectName: "Warehouse Expansion",
    amount: 195000,
    status: "rejected",
    validUntil: "2024-01-30",
    createdDate: "2024-01-05",
    items: [
      { description: "Site preparation", quantity: 1, unitPrice: 35000, total: 35000 },
      { description: "Steel structure", quantity: 1, unitPrice: 95000, total: 95000 },
      { description: "Concrete flooring", quantity: 1, unitPrice: 45000, total: 45000 },
      { description: "Loading dock installation", quantity: 1, unitPrice: 20000, total: 20000 },
    ],
  },
]

export const communications = [
  {
    id: "1",
    clientId: "1",
    clientName: "ABC Construction Ltd.",
    type: "email",
    subject: "Project timeline discussion",
    content: "Discussed the timeline for Phase 2 of the residential building project.",
    date: "2024-01-10",
    user: "Sarah Sales",
  },
  {
    id: "2",
    clientId: "3",
    clientName: "Metro Developers",
    type: "call",
    subject: "Quote follow-up",
    content: "Called to discuss the office complex renovation quote. Client requested minor adjustments.",
    date: "2024-01-12",
    user: "John Manager",
  },
  {
    id: "3",
    clientId: "2",
    clientName: "BuildRight Corp",
    type: "meeting",
    subject: "Site visit and requirements",
    content: "Met at the warehouse site to discuss expansion requirements and constraints.",
    date: "2024-01-08",
    user: "Mike Engineer",
  },
  {
    id: "4",
    clientId: "4",
    clientName: "Urban Builders Inc.",
    type: "email",
    subject: "Invoice payment confirmation",
    content: "Confirmed receipt of payment for Invoice #INV-2024-045.",
    date: "2024-01-05",
    user: "Finance Team",
  },
]

export const projects = [
  {
    id: "PRJ-001",
    name: "Villa Construction - Phase 1",
    clientId: "1",
    clientName: "ABC Construction Ltd.",
    status: "in-progress",
    progress: 65,
    startDate: "2024-01-01",
    endDate: "2024-06-30",
    budget: 450000,
    spent: 292500,
    manager: "John Manager",
    team: ["Mike Engineer", "Sarah Architect", "Tom Builder"],
    description: "Luxury villa construction project including foundation, structure, and finishing work.",
  },
  {
    id: "PRJ-002",
    name: "Office Complex Renovation",
    clientId: "3",
    clientName: "Metro Developers",
    status: "planning",
    progress: 15,
    startDate: "2024-02-01",
    endDate: "2024-08-31",
    budget: 285000,
    spent: 42750,
    manager: "Sarah Manager",
    team: ["Alex Designer", "Chris Engineer"],
    description: "Complete renovation of a 5-story office building including electrical and plumbing upgrades.",
  },
  {
    id: "PRJ-003",
    name: "Residential Building - Phase 2",
    clientId: "1",
    clientName: "ABC Construction Ltd.",
    status: "in-progress",
    progress: 45,
    startDate: "2023-11-01",
    endDate: "2024-05-31",
    budget: 620000,
    spent: 279000,
    manager: "John Manager",
    team: ["Mike Engineer", "Lisa Architect", "Tom Builder", "Emma Electrician"],
    description: "Second phase of residential complex with 24 units.",
  },
  {
    id: "PRJ-004",
    name: "Shopping Mall Expansion",
    clientId: "4",
    clientName: "Urban Builders Inc.",
    status: "on-hold",
    progress: 30,
    startDate: "2023-10-01",
    endDate: "2024-12-31",
    budget: 1200000,
    spent: 360000,
    manager: "David Manager",
    team: ["Robert Engineer", "Nancy Architect"],
    description: "Expansion of existing shopping mall with new wing and parking structure.",
  },
  {
    id: "PRJ-005",
    name: "Warehouse Construction",
    clientId: "2",
    clientName: "BuildRight Corp",
    status: "completed",
    progress: 100,
    startDate: "2023-08-01",
    endDate: "2023-12-31",
    budget: 380000,
    spent: 375000,
    manager: "Sarah Manager",
    team: ["Mike Engineer", "Tom Builder"],
    description: "New warehouse facility with loading docks and office space.",
  },
]

export const projectTasks = [
  {
    id: "1",
    projectId: "PRJ-001",
    title: "Foundation excavation",
    status: "completed",
    priority: "high",
    assignee: "Tom Builder",
    startDate: "2024-01-01",
    endDate: "2024-01-15",
    progress: 100,
  },
  {
    id: "2",
    projectId: "PRJ-001",
    title: "Structural framework",
    status: "in-progress",
    priority: "high",
    assignee: "Mike Engineer",
    startDate: "2024-01-16",
    endDate: "2024-03-15",
    progress: 70,
  },
  {
    id: "3",
    projectId: "PRJ-001",
    title: "Electrical installation",
    status: "pending",
    priority: "medium",
    assignee: "Emma Electrician",
    startDate: "2024-03-16",
    endDate: "2024-04-30",
    progress: 0,
  },
  {
    id: "4",
    projectId: "PRJ-001",
    title: "Plumbing work",
    status: "pending",
    priority: "medium",
    assignee: "Chris Plumber",
    startDate: "2024-04-01",
    endDate: "2024-05-15",
    progress: 0,
  },
  {
    id: "5",
    projectId: "PRJ-001",
    title: "Interior finishing",
    status: "pending",
    priority: "low",
    assignee: "Sarah Architect",
    startDate: "2024-05-16",
    endDate: "2024-06-30",
    progress: 0,
  },
]

export const projectMilestones = [
  {
    id: "1",
    projectId: "PRJ-001",
    title: "Foundation Complete",
    date: "2024-01-15",
    status: "completed",
    description: "All foundation work completed and inspected",
  },
  {
    id: "2",
    projectId: "PRJ-001",
    title: "Structure Complete",
    date: "2024-03-15",
    status: "in-progress",
    description: "Main structural framework completion",
  },
  {
    id: "3",
    projectId: "PRJ-001",
    title: "MEP Installation Complete",
    date: "2024-05-15",
    status: "pending",
    description: "Mechanical, Electrical, and Plumbing systems installed",
  },
  {
    id: "4",
    projectId: "PRJ-001",
    title: "Project Handover",
    date: "2024-06-30",
    status: "pending",
    description: "Final inspection and project handover to client",
  },
]

export const employees = [
  {
    id: "EMP-001",
    name: "John Manager",
    email: "john.manager@sofixe.com",
    phone: "+1 (555) 111-2222",
    position: "Project Manager",
    department: "Projects",
    hireDate: "2020-03-15",
    salary: 85000,
    status: "active",
    skills: ["Project Management", "Construction Planning", "Team Leadership"],
    performance: 4.5,
  },
  {
    id: "EMP-002",
    name: "Sarah Architect",
    email: "sarah.architect@sofixe.com",
    phone: "+1 (555) 222-3333",
    position: "Senior Architect",
    department: "Design",
    hireDate: "2019-06-01",
    salary: 92000,
    status: "active",
    skills: ["AutoCAD", "3D Modeling", "Building Design", "Structural Analysis"],
    performance: 4.8,
  },
  {
    id: "EMP-003",
    name: "Mike Engineer",
    email: "mike.engineer@sofixe.com",
    phone: "+1 (555) 333-4444",
    position: "Civil Engineer",
    department: "Engineering",
    hireDate: "2021-01-10",
    salary: 78000,
    status: "active",
    skills: ["Structural Engineering", "Site Supervision", "Quality Control"],
    performance: 4.3,
  },
  {
    id: "EMP-004",
    name: "Tom Builder",
    email: "tom.builder@sofixe.com",
    phone: "+1 (555) 444-5555",
    position: "Construction Foreman",
    department: "Construction",
    hireDate: "2018-09-20",
    salary: 65000,
    status: "active",
    skills: ["Team Management", "Construction Techniques", "Safety Management"],
    performance: 4.6,
  },
  {
    id: "EMP-005",
    name: "Emma Electrician",
    email: "emma.electrician@sofixe.com",
    phone: "+1 (555) 555-6666",
    position: "Electrical Engineer",
    department: "Engineering",
    hireDate: "2022-02-15",
    salary: 72000,
    status: "active",
    skills: ["Electrical Systems", "Power Distribution", "Lighting Design"],
    performance: 4.4,
  },
  {
    id: "EMP-006",
    name: "Lisa Architect",
    email: "lisa.architect@sofixe.com",
    phone: "+1 (555) 666-7777",
    position: "Architect",
    department: "Design",
    hireDate: "2021-08-01",
    salary: 75000,
    status: "on-leave",
    skills: ["Architectural Design", "Interior Design", "Revit"],
    performance: 4.2,
  },
]

export const payrollRecords = [
  {
    id: "PAY-2024-01",
    month: "January 2024",
    totalPayroll: 467000,
    employeeCount: 156,
    status: "processed",
    processedDate: "2024-01-31",
  },
  {
    id: "PAY-2024-02",
    month: "February 2024",
    totalPayroll: 467000,
    employeeCount: 156,
    status: "pending",
    processedDate: null,
  },
]

export const leaveRequests = [
  {
    id: "LV-001",
    employeeId: "EMP-006",
    employeeName: "Lisa Architect",
    type: "sick",
    startDate: "2024-01-15",
    endDate: "2024-01-20",
    days: 5,
    status: "approved",
    reason: "Medical treatment",
  },
  {
    id: "LV-002",
    employeeId: "EMP-003",
    employeeName: "Mike Engineer",
    type: "vacation",
    startDate: "2024-02-10",
    endDate: "2024-02-17",
    days: 7,
    status: "pending",
    reason: "Family vacation",
  },
  {
    id: "LV-003",
    employeeId: "EMP-001",
    employeeName: "John Manager",
    type: "personal",
    startDate: "2024-01-25",
    endDate: "2024-01-26",
    days: 2,
    status: "approved",
    reason: "Personal matters",
  },
]

export const performanceReviews = [
  {
    id: "REV-001",
    employeeId: "EMP-001",
    employeeName: "John Manager",
    reviewDate: "2024-01-10",
    reviewer: "CEO",
    rating: 4.5,
    strengths: "Excellent project management skills, strong leadership",
    improvements: "Could improve documentation practices",
    goals: "Lead 2 major projects in Q2, mentor junior managers",
  },
  {
    id: "REV-002",
    employeeId: "EMP-002",
    employeeName: "Sarah Architect",
    reviewDate: "2024-01-12",
    reviewer: "Design Director",
    rating: 4.8,
    strengths: "Outstanding design skills, innovative solutions",
    improvements: "Time management on multiple projects",
    goals: "Complete advanced BIM certification, lead design team",
  },
]

export const materials = [
  {
    id: "MAT-001",
    name: "Cement (50kg bags)",
    category: "Building Materials",
    quantity: 450,
    unit: "bags",
    minStock: 200,
    maxStock: 1000,
    unitPrice: 12.5,
    totalValue: 5625,
    location: "Warehouse A",
    supplier: "BuildSupply Co.",
    lastRestocked: "2024-01-08",
    status: "in-stock",
  },
  {
    id: "MAT-002",
    name: "Steel Rebar (12mm)",
    category: "Building Materials",
    quantity: 85,
    unit: "tons",
    minStock: 50,
    maxStock: 200,
    unitPrice: 850,
    totalValue: 72250,
    location: "Warehouse B",
    supplier: "Steel Industries Ltd.",
    lastRestocked: "2024-01-05",
    status: "in-stock",
  },
  {
    id: "MAT-003",
    name: "Concrete Blocks",
    category: "Building Materials",
    quantity: 1200,
    unit: "units",
    minStock: 500,
    maxStock: 3000,
    unitPrice: 3.5,
    totalValue: 4200,
    location: "Warehouse A",
    supplier: "Block Masters",
    lastRestocked: "2024-01-10",
    status: "in-stock",
  },
  {
    id: "MAT-004",
    name: "Paint (Interior)",
    category: "Finishing Materials",
    quantity: 45,
    unit: "gallons",
    minStock: 100,
    maxStock: 300,
    unitPrice: 35,
    totalValue: 1575,
    location: "Warehouse C",
    supplier: "ColorPro Paints",
    lastRestocked: "2023-12-20",
    status: "low-stock",
  },
  {
    id: "MAT-005",
    name: "Electrical Wiring",
    category: "Electrical",
    quantity: 2500,
    unit: "meters",
    minStock: 1000,
    maxStock: 5000,
    unitPrice: 2.5,
    totalValue: 6250,
    location: "Warehouse C",
    supplier: "ElectroSupply Inc.",
    lastRestocked: "2024-01-12",
    status: "in-stock",
  },
  {
    id: "MAT-006",
    name: "PVC Pipes (4 inch)",
    category: "Plumbing",
    quantity: 180,
    unit: "meters",
    minStock: 200,
    maxStock: 800,
    unitPrice: 8.5,
    totalValue: 1530,
    location: "Warehouse B",
    supplier: "Pipe Solutions",
    lastRestocked: "2024-01-03",
    status: "low-stock",
  },
]

export const equipment = [
  {
    id: "EQP-001",
    name: "Excavator CAT 320",
    category: "Heavy Machinery",
    status: "available",
    condition: "good",
    location: "Site A",
    assignedTo: "PRJ-001",
    assignedProject: "Villa Construction - Phase 1",
    purchaseDate: "2022-03-15",
    lastMaintenance: "2024-01-05",
    nextMaintenance: "2024-04-05",
    value: 125000,
  },
  {
    id: "EQP-002",
    name: "Concrete Mixer",
    category: "Machinery",
    status: "in-use",
    condition: "excellent",
    location: "Site B",
    assignedTo: "PRJ-003",
    assignedProject: "Residential Building - Phase 2",
    purchaseDate: "2021-08-20",
    lastMaintenance: "2024-01-10",
    nextMaintenance: "2024-03-10",
    value: 15000,
  },
  {
    id: "EQP-003",
    name: "Tower Crane",
    category: "Heavy Machinery",
    status: "in-use",
    condition: "good",
    location: "Site B",
    assignedTo: "PRJ-003",
    assignedProject: "Residential Building - Phase 2",
    purchaseDate: "2020-05-10",
    lastMaintenance: "2023-12-28",
    nextMaintenance: "2024-02-28",
    value: 285000,
  },
  {
    id: "EQP-004",
    name: "Welding Machine",
    category: "Tools",
    status: "maintenance",
    condition: "fair",
    location: "Warehouse B",
    assignedTo: null,
    assignedProject: null,
    purchaseDate: "2019-11-15",
    lastMaintenance: "2024-01-12",
    nextMaintenance: "2024-02-12",
    value: 3500,
  },
  {
    id: "EQP-005",
    name: "Forklift",
    category: "Machinery",
    status: "available",
    condition: "excellent",
    location: "Warehouse A",
    assignedTo: null,
    assignedProject: null,
    purchaseDate: "2023-02-20",
    lastMaintenance: "2024-01-08",
    nextMaintenance: "2024-04-08",
    value: 28000,
  },
]

export const stockTransactions = [
  {
    id: "TXN-001",
    type: "in",
    materialId: "MAT-001",
    materialName: "Cement (50kg bags)",
    quantity: 200,
    date: "2024-01-08",
    reference: "PO-2024-015",
    notes: "Regular restock from BuildSupply Co.",
  },
  {
    id: "TXN-002",
    type: "out",
    materialId: "MAT-001",
    materialName: "Cement (50kg bags)",
    quantity: 150,
    date: "2024-01-10",
    reference: "PRJ-001",
    notes: "Allocated to Villa Construction project",
  },
  {
    id: "TXN-003",
    type: "in",
    materialId: "MAT-005",
    materialName: "Electrical Wiring",
    quantity: 1000,
    date: "2024-01-12",
    reference: "PO-2024-018",
    notes: "Bulk purchase for upcoming projects",
  },
  {
    id: "TXN-004",
    type: "out",
    materialId: "MAT-003",
    materialName: "Concrete Blocks",
    quantity: 500,
    date: "2024-01-11",
    reference: "PRJ-003",
    notes: "Delivered to Residential Building site",
  },
]

export const warehouses = [
  {
    id: "WH-A",
    name: "Warehouse A",
    location: "North District",
    capacity: 5000,
    occupied: 3200,
    manager: "Tom Builder",
    categories: ["Building Materials", "Finishing Materials"],
  },
  {
    id: "WH-B",
    name: "Warehouse B",
    location: "East District",
    capacity: 4000,
    occupied: 2800,
    manager: "Mike Engineer",
    categories: ["Building Materials", "Heavy Equipment"],
  },
  {
    id: "WH-C",
    name: "Warehouse C",
    location: "South District",
    capacity: 3000,
    occupied: 1500,
    manager: "Emma Electrician",
    categories: ["Electrical", "Plumbing", "Finishing Materials"],
  },
]
