# Generated by Django 5.2.6 on 2026-04-14 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expense_notes_expense_paid_by_expense_payment_date_and_more'),
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('task_name', models.CharField(max_length=200, verbose_name='Nom de Tâche')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='Date de demande')),
                ('period', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel'), ('one_time', 'Ponctuel')], max_length=20, verbose_name='Période')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total demandé')),
                ('description', models.TextField(verbose_name='Motif / description')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='draft', max_length=20)),
                ('validation_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_requests', to='projects.project')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_operations', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'opération",
                'verbose_name_plural': "Demandes d'opération",
                'ordering': ['-request_date'],
            },
        ),
    ]
