# Generated by Django 5.2.6 on 2026-04-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_operationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationrequest',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/%d/', verbose_name='Justificatif de paiement'),
        ),
        migrations.AlterField(
            model_name='operationrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('validated', 'Validé'), ('paid', 'Payé'), ('rejected', 'Rejeté')], default='draft', max_length=20),
        ),
    ]
