# Generated by Django 5.2.6 on 2026-04-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_add_payment_proof_to_operationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cash_withdrawal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de prélèvement caisse'),
        ),
        migrations.AddField(
            model_name='expense',
            name='fund_source',
            field=models.CharField(blank=True, choices=[('project_budget', 'Budget projet'), ('operation_cash', 'Caisse opérations'), ('emergency_fund', "Fonds d'urgence"), ('other', 'Autre')], default='project_budget', max_length=50, verbose_name='Source du fonds'),
        ),
        migrations.AddField(
            model_name='expense',
            name='linked_disbursement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_expenses', to='finance.expense', verbose_name='Décaissement lié'),
        ),
        migrations.AddField(
            model_name='expense',
            name='subcategory',
            field=models.CharField(blank=True, help_text="Sous-catégorie optionnelle (ex: 'Papeterie' pour Matériaux)", max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('under_review', 'En révision'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='draft', max_length=20),
        ),
    ]
