# Generated by Django 5.2.6 on 2026-04-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_expense_cash_withdrawal_date_expense_fund_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationrequest',
            name='category',
            field=models.CharField(blank=True, choices=[('materials', 'Matériaux'), ('labor', "Main d'œuvre"), ('equipment', 'Équipement'), ('transport', 'Transport'), ('utilities', 'Services'), ('consulting', 'Consulting'), ('software', 'Logiciels'), ('other', 'Autre')], max_length=50, verbose_name='Catégorie budgétaire'),
        ),
        migrations.AddField(
            model_name='operationrequest',
            name='subcategory',
            field=models.CharField(blank=True, help_text="Sous-catégorie optionnelle (ex: 'Papeterie' pour Matériaux)", max_length=100, verbose_name='Sous-catégorie'),
        ),
    ]
