# Generated by Django 5.2.6 on 2026-04-19 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_operationrequest_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la sous-catégorie')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (GNF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='finance.operationrequest', verbose_name="Demande d'opération")),
            ],
            options={
                'verbose_name': "Sous-catégorie d'opération",
                'verbose_name_plural': "Sous-catégories d'opération",
                'ordering': ['created_at'],
            },
        ),
    ]
