# Generated by Django 5.2.6 on 2026-04-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_operationsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationrequest',
            name='category',
            field=models.CharField(blank=True, help_text="Catégories séparées par des virgules (ex: 'materials,labor,equipment')", max_length=200, verbose_name='Catégorie(s) budgétaire(s)'),
        ),
    ]
