# Generated by Django 5.2.6 on 2026-04-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_operationrequest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='subcategories',
            field=models.JSONField(blank=True, default=list, help_text='Liste JSON des sous-catégories avec montants'),
        ),
    ]
