# Generated by Django 5.2.6 on 2026-04-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_expense_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='operationrequest',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='OperationSubcategory',
        ),
    ]
